version: '2'

services:
  # Application
  app:
    extends:
      file: docker-compose-common.yml
      service: web
    container_name: app
    ports:
      - 80:80
    working_dir: /usr/src/application
    depends_on:
      - db
    networks:
      app:
        aliases:
          - laravel.local

  # DB
  db:
#    build: ./container/db/mysql
    image: mysql:5.7
    container_name: db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./container/db/mysql/volumes/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER:          root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:      test
      MYSQL_PASSWORD:      password
      TZ: JST-9
    networks:
      - app

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    ports:
      - 8080:80
    volumes:
      - ./container/phpmyadmin/sessions:/sessions

  # Selenium TestBrowser (Chrome)
  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
      - 5900:5900
    links:
      - app:laravel.local
    networks:
      app:
        aliases:
          - selenium.local

networks:
  app: